### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Nicolasmar91** [Nicolasmar91/FoxConvert#3]
Créer des fichier units.json pour chaque langue
finir de saisir les données
faire un wiki

**Comment by indydedeken** [comment]
- Créer des fichier units.json pour chaque langue > Je ne sais pas si tu connais [https://developer.mozilla.org/en-US/Apps/Build/Localization/Getting_started_with_app_localization](https://developer.mozilla.org/en-US/Apps/Build/Localization/Getting_started_with_app_localization)

Idées : 
- changer la font
- mettre le pluriel (ex : conversion octet vers bit -> 8bit**S**) ;)

Sympa l'app

**Comment by Nicolasmar91** [comment]
Hello, merci pour ton message.

Ben sans le savoir j'ai réinventé la manière de faire de mozilla pour les
traduction, je procède selon la même logique.

Pour la font il me semble avoir utilisé celle de Firefox OS

(Merci pour la petite erreur ;) )

Thanks !

**Comment by Desiderius77** [comment]
Fabien Cazenave a développé et maintient une librairie pour faire ça facilement : 
https://github.com/fabi1cazenave/webL10n
